networks:
  app-network:
    driver: bridge

volumes:
  pg-data:

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3000:${APP_PORT:-8080}
    env_file:
      - .env
    volumes:
      - ./internal/database/gen/dbstore:/app/database/gen/dbstore
      - ./internal/database/queries:/app/database/queries
    depends_on:
      - postgres
    networks:
      - app-network
    
  postgres:
    image: postgres:17.5-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_DATABASE:-app}
      POSTGRES_USER: ${DB_PORT:-forge}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - pg-data:/var/lib/postgresql/data:cached
    ports:
      - 5436:${DB_PORT:-5432}
    networks:
      - app-network